-- Segment 2: catalog schema.
--
-- Ownership hierarchy: City -> Theater -> Screen -> Seat (structural layout,
-- managed implicitly: seats are generated when a screen is created, never
-- created directly). Independently: Movie -> Show -> ShowSeat (one ShowSeat
-- row per seat per show; this is the per-show seat inventory that Segment 3's
-- hold/booking logic operates on).
--
-- Delete semantics are deliberate, not incidental:
--   - city -> theater -> screen -> seat cascade on delete (pure ownership;
--     removing a city should remove everything structurally beneath it).
--   - show -> show_seat cascades on delete (removing a show removes its
--     per-show inventory).
--   - movie -> show and screen -> show are RESTRICT: you cannot delete a
--     movie or screen that already has shows scheduled against it.
--   - seat -> show_seat is RESTRICT: a seat that has ever been part of a show
--     cannot be deleted. Combined with the cascade above, this means deleting
--     a city/theater/screen transitively fails (as a single FK violation,
--     surfaced as 409 Conflict) once any show has ever been scheduled on one
--     of its screens -- the catalog's structural skeleton can't be torn down
--     out from under historical show data.

CREATE TABLE cities (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(120) NOT NULL,
    state      VARCHAR(120),
    country    VARCHAR(120),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE theaters (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city_id    BIGINT NOT NULL REFERENCES cities (id) ON DELETE CASCADE,
    name       VARCHAR(150) NOT NULL,
    address    VARCHAR(300),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_theaters_city_id ON theaters (city_id);

CREATE TABLE screens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    theater_id BIGINT NOT NULL REFERENCES theaters (id) ON DELETE CASCADE,
    name       VARCHAR(100) NOT NULL,
    -- Row labels are single letters (A-Z), so a screen is capped at 26 rows.
    -- Ample for the assignment's scale; multi-letter labels (AA, AB, ...) are
    -- not implemented.
    total_rows INT NOT NULL CHECK (total_rows BETWEEN 1 AND 26),
    total_cols INT NOT NULL CHECK (total_cols BETWEEN 1 AND 100),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_screens_theater_id ON screens (theater_id);

CREATE TABLE seats (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    screen_id   BIGINT NOT NULL REFERENCES screens (id) ON DELETE CASCADE,
    row_label   VARCHAR(2) NOT NULL,
    seat_number INT NOT NULL,
    category    VARCHAR(20) NOT NULL CHECK (category IN ('REGULAR', 'PREMIUM')),
    UNIQUE (screen_id, row_label, seat_number)
);
CREATE INDEX idx_seats_screen_id ON seats (screen_id);

CREATE TABLE movies (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title            VARCHAR(200) NOT NULL,
    duration_minutes INT NOT NULL CHECK (duration_minutes > 0),
    language         VARCHAR(50),
    genre            VARCHAR(50),
    rating           VARCHAR(10),
    description      VARCHAR(1000),
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE shows (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movie_id   BIGINT NOT NULL REFERENCES movies (id) ON DELETE RESTRICT,
    screen_id  BIGINT NOT NULL REFERENCES screens (id) ON DELETE RESTRICT,
    start_time TIMESTAMPTZ NOT NULL,
    end_time   TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    -- Soft guard against scheduling two shows on the same screen at the exact
    -- same instant. This does NOT detect general time-range overlap (e.g. a
    -- show starting mid-way through another) -- that validation is out of
    -- scope for this assignment and is left as an admin responsibility.
    UNIQUE (screen_id, start_time)
);
CREATE INDEX idx_shows_screen_id ON shows (screen_id);
CREATE INDEX idx_shows_movie_id ON shows (movie_id);

-- Per-show seat inventory. One row per (show, seat). Status starts and stays
-- AVAILABLE in Segment 2; HELD/BOOKED/CANCELLED are exercised starting in
-- Segment 3, which also ALTERs this table to add the hold-tracking columns
-- (held_by, hold_expires_at) needed by the atomic hold UPDATE.
CREATE TABLE show_seats (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    show_id    BIGINT NOT NULL REFERENCES shows (id) ON DELETE CASCADE,
    seat_id    BIGINT NOT NULL REFERENCES seats (id) ON DELETE RESTRICT,
    status     VARCHAR(20) NOT NULL DEFAULT 'AVAILABLE'
                   CHECK (status IN ('AVAILABLE', 'HELD', 'BOOKED', 'CANCELLED')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (show_id, seat_id)
);
CREATE INDEX idx_show_seats_show_id ON show_seats (show_id);
-- Composite index supports both "available seats for show X" (Segment 2) and
-- the hold/expiry sweep (Segment 3).
CREATE INDEX idx_show_seats_show_status ON show_seats (show_id, status);
