-- V5__segment4_pricing_bookings.sql
--
-- Segment 4: pricing tiers, discount codes, and booking confirmation.
--
-- Design notes:
--   - PricingTier is linked to shows via a nullable FK. A show without a pricing
--     tier cannot be booked; assigning one is an explicit admin action. We seed a
--     default "Standard" tier and assign it to all existing V3 shows so they are
--     immediately bookable in Swagger UI.
--   - UNIQUE on bookings.show_seat_id is the hard backstop against double-booking,
--     complementing the atomic conditional UPDATE from Segment 3.
--   - bookings.idempotency_key uniqueness prevents duplicate payment processing.
--   - discount_codes.max_uses NULL means unlimited uses.

CREATE TABLE pricing_tiers (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name               VARCHAR(100)  NOT NULL,
    regular_price      NUMERIC(10,2) NOT NULL CHECK (regular_price >= 0),
    premium_price      NUMERIC(10,2) NOT NULL CHECK (premium_price >= 0),
    weekend_multiplier NUMERIC(4,2)  NOT NULL DEFAULT 1.00 CHECK (weekend_multiplier >= 1.00),
    created_at         TIMESTAMPTZ   NOT NULL DEFAULT now()
);

CREATE TABLE discount_codes (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code          VARCHAR(50)   NOT NULL UNIQUE,
    discount_type VARCHAR(20)   NOT NULL CHECK (discount_type IN ('PERCENTAGE', 'FLAT')),
    value         NUMERIC(10,2) NOT NULL CHECK (value > 0),
    max_uses      INT,
    current_uses  INT           NOT NULL DEFAULT 0,
    valid_from    TIMESTAMPTZ,
    valid_to      TIMESTAMPTZ,
    active        BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ   NOT NULL DEFAULT now()
);

CREATE TABLE bookings (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer         VARCHAR(100)  NOT NULL,
    show_id          BIGINT        NOT NULL REFERENCES shows (id) ON DELETE RESTRICT,
    show_seat_id     BIGINT        NOT NULL UNIQUE REFERENCES show_seats (id) ON DELETE RESTRICT,
    pricing_tier_id  BIGINT        NOT NULL REFERENCES pricing_tiers (id) ON DELETE RESTRICT,
    discount_code_id BIGINT        REFERENCES discount_codes (id) ON DELETE RESTRICT,
    base_price       NUMERIC(10,2) NOT NULL,
    discount_amount  NUMERIC(10,2) NOT NULL DEFAULT 0,
    final_price      NUMERIC(10,2) NOT NULL,
    status           VARCHAR(20)   NOT NULL
                         CHECK (status IN ('PAYMENT_PENDING', 'CONFIRMED', 'PAYMENT_FAILED', 'CANCELLED')),
    idempotency_key  VARCHAR(100)  NOT NULL UNIQUE,
    created_at       TIMESTAMPTZ   NOT NULL DEFAULT now(),
    confirmed_at     TIMESTAMPTZ
);
CREATE INDEX idx_bookings_customer ON bookings (customer);
CREATE INDEX idx_bookings_show_id ON bookings (show_id);

-- Nullable: shows created before any pricing tier exists can still be saved;
-- booking attempt on an unpriced show returns 400 with a clear message.
ALTER TABLE shows ADD COLUMN pricing_tier_id BIGINT REFERENCES pricing_tiers (id) ON DELETE RESTRICT;

-- Seed default tier so the V3 shows are immediately bookable via Swagger.
INSERT INTO pricing_tiers (name, regular_price, premium_price, weekend_multiplier)
VALUES ('Standard', 150.00, 250.00, 1.25);

UPDATE shows SET pricing_tier_id = (SELECT id FROM pricing_tiers WHERE name = 'Standard');
