-- V6__segment5_refunds_notifications.sql
--
-- Segment 5: cancellation, policy-based refunds, and async notifications.
--
-- RefundPolicy is a header row; tiers live in refund_policy_tiers.
-- At cancellation, the tier with the largest hours_before_show that is still
-- <= hours remaining until the show start determines the refund percentage.
--
-- Like pricing_tier_id, refund_policy_id on shows is nullable. A show without
-- a refund policy at cancellation time receives a 0% refund.
--
-- A seeded "Standard Refund Policy" (100%/>24h, 50%/>12h, 0% otherwise) is
-- assigned to all existing shows from V3 so they are immediately cancellable.

CREATE TABLE refund_policies (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(100) NOT NULL,
    is_default BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- Composite PK prevents duplicate tier thresholds within the same policy.
CREATE TABLE refund_policy_tiers (
    policy_id         BIGINT NOT NULL REFERENCES refund_policies (id) ON DELETE CASCADE,
    hours_before_show INT    NOT NULL CHECK (hours_before_show >= 0),
    refund_percent    INT    NOT NULL CHECK (refund_percent BETWEEN 0 AND 100),
    PRIMARY KEY (policy_id, hours_before_show)
);

ALTER TABLE shows
    ADD COLUMN refund_policy_id BIGINT REFERENCES refund_policies (id) ON DELETE RESTRICT;

ALTER TABLE bookings
    ADD COLUMN refund_amount NUMERIC(10, 2),
    ADD COLUMN cancelled_at TIMESTAMPTZ;

-- Seed default policy and wire it to all existing shows.
INSERT INTO refund_policies (name, is_default) VALUES ('Standard Refund Policy', TRUE);

INSERT INTO refund_policy_tiers (policy_id, hours_before_show, refund_percent)
SELECT id, 24, 100 FROM refund_policies WHERE name = 'Standard Refund Policy'
UNION ALL
SELECT id, 12, 50  FROM refund_policies WHERE name = 'Standard Refund Policy'
UNION ALL
SELECT id,  0,  0  FROM refund_policies WHERE name = 'Standard Refund Policy';

UPDATE shows SET refund_policy_id = (SELECT id FROM refund_policies WHERE is_default = TRUE);
